# -*- coding: utf-8 -*-
"""Prodigy Task 4_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCCn5TbjeihhBwDNxBLM6tIq-V_GbdPh

**Prodigy Infotech**

Data Science Intern

**Task-04**

**Task:** Analyze and visualize sentiment patterns in social media data to understand public opinion and attitudes towards specific topics or brands.
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('twitter_training.csv')

data.head()

col_names=['ID','Entity','Sentiment','Content']
df = pd.read_csv('twitter_training.csv',names=col_names)

df.head()

df.shape

df.describe

df.isnull().sum()

df.dropna(axis=0 , inplace=True)

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)
df.duplicated().sum()

sentiment_counts = df['Sentiment'].value_counts()
sentiment_counts

plt.figure(figsize=(6, 3))
sentiment_counts.plot(kind='bar')
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Number of Tweets')
plt.xticks(rotation=0)
plt.show()

brand_data = df[df['Entity'].str.contains('Amazon', case=False)]
brand_sentiment_counts = brand_data['Sentiment'].value_counts()
brand_sentiment_counts

plt.figure(figsize=(6, 6))
plt.pie(brand_sentiment_counts, labels=brand_sentiment_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Sentiment Distribution for Amazon')
plt.show()

brand_data1 = df[df['Entity'].str.contains('Google', case=False)]
brand_sentiment_counts1 = brand_data1['Sentiment'].value_counts()
brand_sentiment_counts1

plt.figure(figsize=(6, 6))
plt.pie(brand_sentiment_counts1, labels=brand_sentiment_counts1.index, autopct='%1.1f%%', startangle=140)
plt.title('Sentiment Distribution for Google')
plt.show()

brand_data2 = df[df['Entity'].str.contains('Microsoft', case=False)]
brand_sentiment_counts2 = brand_data2['Sentiment'].value_counts()
brand_sentiment_counts2

plt.figure(figsize=(6, 6))
plt.pie(brand_sentiment_counts2, labels=brand_sentiment_counts1.index, autopct='%1.1f%%', startangle=140)
plt.title('Sentiment Distribution for Microsoft')
plt.show()

brand_data3 = df[df['Entity'].str.contains('Nvidia', case=False)]
brand_sentiment_counts3 = brand_data3['Sentiment'].value_counts()
brand_sentiment_counts3

plt.figure(figsize=(6, 6))
plt.pie(brand_sentiment_counts3, labels=brand_sentiment_counts1.index, autopct='%1.1f%%', startangle=140)
plt.title('Sentiment Distribution for Nvidia')
plt.show()